SET ANSI_NULLS ON;
SET ANSI_PADDING ON;
SET ANSI_WARNINGS ON;
SET ARITHABORT ON;
SET CONCAT_NULL_YIELDS_NULL ON;
SET NUMERIC_ROUNDABORT OFF;
SET QUOTED_IDENTIFIER ON;
GO
IF OBJECT_ID(N'[dbo].[DeleteMember]',N'P') IS NULL EXECUTE(N'CREATE PROCEDURE [dbo].[DeleteMember] AS RAISERROR(''UNDEFINED!'',16,1);');
GO

ALTER PROCEDURE [dbo].DeleteMember
			@MemberID INT
AS BEGIN
	SET NOCOUNT ON;
	DELETE FROM [dbo].[Members]
	WHERE MemberID = @MemberID
END